export const RESOURCE_LOADING = 'RESOURCE_LOADING';
export const RESOURCE_SUCCESS = 'RESOURCE_SUCCESS';
export const RESOURCE_FAIL = 'RESOURCE_FAIL';
export const SAVE_RESOURCE_DETAILS_LOADING = 'SAVE_RESOURCE_DETAILS_LOADING';
export const SAVE_RESOURCE_DETAILS_SUCCESS = 'SAVE_RESOURCE_DETAILS_SUCCESS';
export const SAVE_RESOURCE_DETAILS_FAIL = 'SAVE_RESOURCE_DETAILS_FAIL';

export const SAVE_STACK = 'SAVE_STACK';
export const SAVE_STACK_LOADING = 'SAVE_STACK_LOADING';
export const SAVE_STACK_SUCCESS = 'SAVE_STACK_SUCCESS';
export const SAVE_STACK_FAIL = 'SAVE_STACK_FAIL';

export const UPDATE_STACK = 'UPDATE_STACK';
export const UPDATE_STACK_LOADING = 'UPDATE_STACK_LOADING';
export const UPDATE_STACK_SUCCESS = 'UPDATE_STACK_SUCCESS';
export const UPDATE_STACK_FAIL = 'UPDATE_STACK_FAIL';

export const STACK_FLUSH_DATA = 'STACK_FLUSH_DATA';
