export const ADD_RESOURCE_LOADING = 'ADD_RESOURCE_LOADING';
export const ADD_RESOURCE_SUCCESS = 'ADD_RESOURCE_SUCCESS';
export const ADD_RESOURCE_FAIL = 'ADD_RESOURCE_FAIL';
export const GET_RESOURCE_FIELDS_SUCCESS = 'GET_RESOURCE_FIELDS_SUCCESS';
export const GET_RESOURCE_FIELDS_FAIL = 'GET_RESOURCE_FIELDS_FAIL';
export const GET_RESOURCE_FIELDS_LOADING = 'GET_RESOURCE_FIELDS_LOADING';

export const SITES_AND_CATEGORIES = 'SITES_AND_CATEGORIES';
export const SITES_AND_CATEGORIES_LOADING = 'SITES_AND_CATEGORIES_LOADING';
export const SITES_AND_CATEGORIES_SUCCESS = 'SITES_AND_CATEGORIES_SUCCESS';
export const SITES_AND_CATEGORIES_FAIL = 'SITES_AND_CATEGORIES_FAIL';
